version: "3.3"

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  stirling-pdf:
    container_name: stirling-pdf
    image: frooodle/s-pdf:latest
    restart: unless-stopped
    volumes:
      - ./config/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./config/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
    networks:
      homelab:
        ipv4_address: 10.1.5.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.pdf.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pdf.tls=true
      - traefik.http.routers.pdf.tls.certresolver=cloudflare
      - traefik.http.routers.pdf.entrypoints=websecure
