networks:
  proxy:
    name: proxy
    external: true

volumes:
  portainer_data:
    name: portainer_data

services:
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      proxy:
    ports:
      - "9443:9443"
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=cloudflare
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
