name: grafana

networks:
  proxy:
    name: proxy
    external: true

volumes:
  grafana:

services:
  grafana-enterprise:
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    networks:
      proxy:
    image: grafana/grafana-enterprise
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=cloudflare
      - traefik.http.services.grafana.loadbalancer.server.port=3000
