name: cups
services:
  cupsd:
    container_name: cups
    restart: unless-stopped
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/cups:/var/run/cups
      - /etc/cups:/etc/cups
    privileged: true
    image: anujdatar/cups
