version: '3'

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ../config/homarr/configs:/app/data/configs
      - ../config/homarr/icons:/app/public/icons
      - ../config/homarr/data:/data
    networks:
      homelab:
        ipv4_address: 10.1.3.1
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.homarr.tls=true
      - traefik.http.routers.homarr.tls.certresolver=cloudflare
      - traefik.http.services.homarr.loadbalancer.server.port=7575