networks:
  proxy:
    name: proxy
    external: true

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: "${IMAGE}:latest"
    volumes:
      - "../config/pihole-unbound:/opt/unbound/etc/unbound/unbound.log"
    networks:
      proxy:

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      proxy:
    environment:
      TZ: "${TZ}"
      DNSSEC: false
      CUSTOM_CACHE_SIZE: 0
      DNS1: unbound
      DNS2: unbound
      WEBPASSWORD: "${WEBPASSWORD}"
      QUERY_LOGGING: false
    volumes:
      - "../config/pihole-unbound/pihole:/etc/pihole"
      - "../config/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=cloudflare
      - traefik.http.services.pihole.loadbalancer.server.port=80