version: "3.3"

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: "${IMAGE}:latest"
    networks:
      homelab:
        ipv4_address: 10.1.7.1

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      homelab:
        ipv4_address: 10.1.7.2
    environment:
      ServerIP: 10.1.7.2
      TZ: "${TZ}"
      DNSSEC: false
      CUSTOM_CACHE_SIZE: 0
      DNS1: 10.1.7.1 # Point to unbound
      DNS2: 10.1.7.1 # Also the second defined, otherwise it auto selects Google DNS
      WEBPASSWORD: "${WEBPASSWORD}"
      QUERY_LOGGING: false
    volumes:
      - "./config/pihole:/etc/pihole"
      - "./config/dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=cloudflare
      - traefik.http.services.pihole.loadbalancer.server.port=80