networks:
  proxy:
    name: proxy
    external: true

volumes:
  pihole-pihole:
  pihole-dnsmasq:
  unbound:

services:
  unbound:
    container_name: unbound
    restart: unless-stopped
    image: "${IMAGE}:latest"
    volumes:
      - "unbound:/etc/unbound"
    networks:
      proxy:
        ipv4_address: 10.0.0.30

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "8090:80"
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      proxy:
        ipv4_address: 10.0.0.20
    environment:
      TZ: "${TZ}"
      DNSSEC: false
      CUSTOM_CACHE_SIZE: 0
      DNS1: unbound
      DNS2: unbound
      WEBPASSWORD: "${WEBPASSWORD}"
      QUERY_LOGGING: false
    volumes:
      - "pihole-pihole:/etc/pihole"
      - "pihole-dnsmasq:/etc/dnsmasq.d"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=cloudflare
      - traefik.http.services.pihole.loadbalancer.server.port=80
