networks:
  proxy:
    name: proxy
    external: true

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
    restart: unless-stopped
