version: '3'

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:  
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # - PEERS=${PEERS}
      - PEERDNS=10.1.7.2 # Point to pihole instance
    volumes:
      - ../config/wireguard:/config
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.1.8.1
