version: '3'

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  homer:
    image: 'b4bz/homer:latest'
    container_name: homer-dash
    volumes:
      - ./config/www/assets:/www/assets
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.1.3.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.homer.tls=true
      - traefik.http.routers.homer.tls.certresolver=cloudflare
      - traefik.http.routers.homer.entrypoints=websecure
      

