---
version: "3"

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    networks:
      homelab:
        ipv4_address: 10.1.8.1
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_HOSTNAMES=${VPN_HOSTNAMES}
    volumes:
      - ./config/gluetun:/gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=false

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbt.rule=Host(`${QBITTORRENT_DOMAIN}`)
      - traefik.http.routers.qbt.tls=true
      - traefik.http.routers.qbt.tls.certresolver=cloudflare
      - traefik.http.services.qbt.loadbalancer.server.port=8080

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=cloudflare
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
  
  plex:
    container_name: plex
    ports:
        # WebUI
        - '32400:32400/tcp'
        # Companion Apps
        - '3005:3005/tcp'
        # Plex for Roku Companion
        # - '8324:8324/tcp'
        # DLNA Server
        # - '32469:32469/tcp'
        # - '1900:1900/udp'
        # Network discovery
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    networks:
      homelab:
        ipv4_address: 10.1.8.3
    environment:
        - TZ=${TZ}
        - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
        - ./config/plex:/config
        - ./config/plex/transcode:/transcode
        - ${DRIVE_PATH}:/media
    devices:
      - /dev/dri:/dev/dri
    image: plexinc/pms-docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`${PLEX_DOMAIN}`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ./config/overseerr:/app/config
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.1.8.2
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.overseerr-rtr.rule=Host(`${OVERSEERR_DOMAIN}`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"      
      - "traefik.http.routers.overseerr-rtr.tls.certresolver=cloudflare"
      ## HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - ./config/prowlarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_DOMAIN}`)
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=cloudflare
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

