---
version: "3"

networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    networks:
      homelab:
        ipv4_address: 10.1.8.1
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRY}
    volumes:
      - ./config/gluetun:/gluetun
    labels:
      - com.centurylinklabs.watchtower.enable=false

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ./config/jackett:/config
      - ./config/jackett/blackhole:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`${JACKETT_DOMAIN}`)
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.tls.certresolver=cloudflare
      - traefik.http.services.jackett.loadbalancer.server.port=9117

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbt.rule=Host(`${QBITTORRENT_DOMAIN}`)
      - traefik.http.routers.qbt.tls=true
      - traefik.http.routers.qbt.tls.certresolver=cloudflare
      - traefik.http.services.qbt.loadbalancer.server.port=8080

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/bazarr:/config
      - ${DRIVE_PATH}:/nas
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=Host(`${BAZARR_DOMAIN}`)
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=cloudflare
      - traefik.http.services.bazarr.loadbalancer.server.port=6767

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=cloudflare
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
  
  plex:
    container_name: plex
    ports:
        # WebUI
        - '32400:32400/tcp'
        # Companion Apps
        - '3005:3005/tcp'
        # Plex for Roku Companion
        # - '8324:8324/tcp'
        # DLNA Server
        - '32469:32469/tcp'
        - '1900:1900/udp'
        # Network discovery
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    networks:
      homelab:
        ipv4_address: 10.1.8.2
    environment:
        - TZ=${TZ}
        - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
        - ./config/plex:/config
        - ./config/plex/transcode:/transcode
        - ${DRIVE_PATH}:/media
    image: plexinc/pms-docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`${PLEX_DOMAIN}`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=cloudflare
      - traefik.http.services.plex.loadbalancer.server.port=32400
