services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - SERVER_COUNTRIES=${VPN_COUNTRIES}
    volumes:
      - ${CONFIG_PATH}/gluetun:/gluetun
    ports:
      - "8080:8080"
      - "7878:7878"
      - "8989:8989"
      - "9696:9696"
    labels:
      - com.centurylinklabs.watchtower.enable=false

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG_PATH}/qbittorrent:/config
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DRIVE_PATH}:/nas
      - ${DRIVE_PATH}/Downloads:/downloads
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  plex:
    container_name: plex
    hostname: plex
    restart: unless-stopped
    ports:
      - "32400:32400"
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${CONFIG_PATH}/plex/transcode:/transcode
      - ${DRIVE_PATH}:/media
    devices:
      - /dev/dri:/dev/dri
    image: plexinc/pms-docker

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055"
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/overseerr:/app/config
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  flaresolverr:
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    depends_on:
      gluetun:
        condition: service_healthy
