networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000 # -- optional, your user id
      PGID: 992 # -- optional, your group id
    networks:
      homelab:
        ipv4_address: 10.1.5.1
    volumes:
      - ../config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker integration
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${HOMEPAGE_DOMAIN}`)
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cloudflare
      - traefik.http.services.homepage.loadbalancer.server.port=3000
