networks:
  proxy:
    name: proxy
    external: true

volumes:
  pihole-pihole:
  pihole-dnsmasq:
  unbound:

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      proxy:
        ipv4_address: 10.0.0.20
    environment:
      TZ: "${TZ}"
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      WEBPASSWORD: "${WEBPASSWORD}"
      QUERY_LOGGING: false
    volumes:
      - "pihole-pihole:/etc/pihole"
      - "pihole-dnsmasq:/etc/dnsmasq.d"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=cloudflare
      - traefik.http.services.pihole.loadbalancer.server.port=80
