networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true


services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - ../config/paperless-ngx/redis:/data
    networks:
      - homelab


  paperlessdb:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    volumes:
      - ../config/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - homelab


  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperlessdb
      - broker
    # ports:
    #   - "8000:8000"
    networks:
      - homelab
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../config/paperless-ngx/paperless-data:/usr/src/paperless/data
      - ../config/paperless-ngx/paperless-media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: paperlessdb
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless.rule=Host(`paperless.rubenclaessens.nl`)
      - traefik.http.routers.paperless.tls=true
      - traefik.http.routers.paperless.tls.certresolver=cloudflare
      - traefik.http.services.paperless.loadbalancer.server.port=8000

