---
- name: Update APT package cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true

- name: Check if reboot required
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Debug reboot required
  ansible.builtin.debug:
    msg: "Machine {{ ansible_hostname }} needs a reboot: {{ reboot_required.stat.exists }}"

- name: Reboot the machine when required
  become: true
  ansible.builtin.reboot:
  when: reboot_required.stat.exists
