networks:
  proxy:
    name: proxy
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  letsencrypt:


services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_API_TOKEN=${CF_API_TOKEN}
    volumes:
      # Volume for letsencypt acme
      - letsencrypt:/letsencrypt:rw
      # Configuration file
      - .:/etc/traefik
      # Reading the docker sock for configuring services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Dynamic configuration file
      - ./dynamic.yml:/config/dynamic.yml
    networks:
      proxy:
        ipv4_address: 10.0.0.10
