---
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ../config/netboot.xyz/config:/config
      - ../config/netboot.xyz/assets:/assets
    ports:
      - 3000:3000 # Web UI
      - 69:69/udp # TFTP Server
    restart: unless-stopped