networks:
  proxy:
    name: proxy
    external: true

services:
  server:
    container_name: vaultwarden
    image: "vaultwarden/server:latest"
    volumes:
      - "../config/vaultwarden/vw-data/:/data/"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.vaultwarden.tls.certresolver=cloudflare
      - traefik.http.routers.vaultwarden.tls=true
