networks:
  proxy:
    name: proxy
    external: true

services:
  server:
    container_name: vaultwarden
    image: "vaultwarden/server:latest"
    volumes:
      - "../config/vaultwarden/:/data"
      - "../config/vaultwarden/logs:/data/logs"
    restart: unless-stopped
    environment:
      - DOMAIN=https://${DOMAIN_NAME}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
      - LOG_FILE=/data/logs/access.log
      - WEB_VAULT_ENABLED=${WEB_VAULT_ENABLED}
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.vaultwarden.tls.certresolver=cloudflare
      - traefik.http.routers.vaultwarden.tls=true
