services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ../config/duplicati/config:/config
      - ../config/duplicati/backups:/backups
      - ${DOCKER_CONFIG_PATH}:/docker-configs
    restart: unless-stopped