networks:
  homelab:
    name: homelab
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/16"
    external: true


services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    networks:
      homelab:
        ipv4_address: 10.1.9.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.postgres.rule=Host(`${PG_DOMAIN}`)
      - traefik.http.routers.postgres.tls=true
      - traefik.http.routers.postgres.tls.certresolver=cloudflare
      - traefik.http.routers.postgres.entrypoints=websecure
      - traefik.http.services.postgres.loadbalancer.server.port=5432
